### ISSUE TITLE
iron-webcrypto Loader error & Cannot read properties of undefined (reading 'onError')

### ISSUE THREAD

**Issue by gokalpfirat** [nuxt/bridge#710]
### Environment

------------------------------
- Operating System: `Linux`
- Node Version:     `v16.14.2`
- Nuxt Version:     `2.16.1`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@7.17.0`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`, `bridge`, `serverHandlers`, `devServerHandlers`, `devServer`, `typescript`
- Runtime Modules:  `-`
- Build Modules:    `()`, `@nuxt/bridge@3.0.0-27928371.c30fa0f`
------------------------------

### Reproduction

Just created a Nuxt 2 project and migrate it to Nuxt bridge step-by-step using Readme file

Nitro server disabled from bridge options

https://stackblitz.com/edit/nuxt-bridge-h3-issues

### Describe the bug

First error caused by `iron-webcrypto` package, which is used by unplugin under the hood. Unplugin build packages targeting ESNext therefore Nullish coalescing operator won't get tranpiled and cause errors at Nuxt side.

If we add  `iron-webcrypto` into nuxt configs transpile option `build: { transpile: ['iron-webcrypto'] }` the error will be fixed but I think it should be automatically added by bridge module for new users.

Second error is a breaking and can't be fixed with any nuxt options I guess. With latest version of nuxi the dev command breaks because of server handler is written for h3 http framework but nuxt 2 with nitro option turned off works with connect http package.

You can see the change at the commit at the `packages/nuxi/src/commands/dev.ts` file https://github.com/nuxt/nuxt/commit/895ecc7677313e6653136eb834a5b6bd78e9329b

`currentHandler = currentNuxt.server.app` is changed to `currentHandler = toNodeListener(currentNuxt.server.app)`

Newest handler uses function toNodeListener which is used to convert h3 based server app to request listener to use at such as node's http package.

Nuxt 2 uses connect http framework so I think toNodeListener for this case shouldn't be happening, if I change it back it's working like before. For a temporary fix I added a downgraded version of nuxi which has not that commit.

### Logs

```shell
ERROR  in ./node_modules/iron-webcrypto/dist/index.js                                            friendly-errors 00:34:00

Module parse failed: Unexpected token (146:29)                                                    friendly-errors 00:34:00
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|   const algorithm = algorithms[options.algorithm];
|   const result = {};
>   const hmac = options.hmac ?? false;
|   const id = hmac ? { name: "HMAC", hash: algorithm.name } : { name: algorithm.name };
|   const usage = hmac ? ["sign", "verify"] : ["encrypt", "decrypt"];
                                                                                                  friendly-errors 00:34:00
 @ ./node_modules/h3/dist/index.mjs 108:0-56 1233:17-21 1233:105-113 1257:17-23 1257:106-114
 @ ./node_modules/@nuxt/bridge/dist/runtime/composables.mjs
 @ ./node_modules/@nuxt/bridge/dist/runtime/index.mjs
 @ ./.nuxt/capi.plugin.mjs
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js```


```
 ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'onError')
```
```

**Comment by pawmanaloto** [comment]
I have the same issue, how did you downgrade your nuxi?

**Comment by gbyesiltas** [comment]
I'm also having the same issue 👍

**Comment by gokalpfirat** [comment]
> I have the same issue, how did you downgrade your nuxi?

Add nuxi@3.0.0-rc.8 as dev dependency

**Comment by Aleksandr-Baranchuk** [comment]
I have the same problem.

- Operating System: macOS
- Node Version: v16.16.0
- Nuxt Version: 2.16.0
- Nitro Version: 1.0.0
- Package Manager: yarn@1.22.19
- Builder: webpack
- Build Modules: @nuxt/bridge@3.0.0-27928371.c30fa0f

**Comment by gmcinalli** [comment]
> Add nuxi@3.0.0-rc.8 as dev dependency

@gokalpfirat I've downgraded `nuxi` to the `3.0.0.-rc.8` but I still have this problem.

**Comment by hatakuya** [comment]
Hi. I had the same problem trying to update an old bridge used project.

Perhaps the Nuxt Bridge could be  really JUST A BRIDGE until the Nuxtjs3 stable comes out.Changes always look destructive and 'npm audit' doesn't make sense.

According to the upgrade guide, Not yet only Bridge is stable. 
https://nuxt.com/docs/getting-started/upgrade

When I changed 2 -> bridge (around 2022/4), the semi-stable status was bridge and 3.The case migrating from 2 now, I looked like the best approach will be to skip the bridge and update directly to 3.

Nevertheless if you want to try the bridge, you can also to apply the "nuxt-edge" package instead of "nuxt".
I used this package in my project.

https://www.npmjs.com/package/nuxt-edge?activeTab=versions

Sample:

```
"devDependencies": {
    "@nuxt/bridge": "npm:@nuxt/bridge-edge@^3.0.0-27928371.c30fa0f",
    "core-js": "^3.28.0",
    "nuxt-edge": "^2.16.1-27937458.a4ac738"
  }
```

But it is unclear whether the latest update and other packages are synchronized.
I was having a hard time this, so I hope this some ones help.

**Comment by Aleksandr-Baranchuk** [comment]
Maybe this will be useful for someone, it solved the problem for me.

```
rm yarn.lock
yarn cache clean
rm -rf node_modules/
yarn install
```

nuxt.config

```
build: {
  transpile: ['iron-webcrypto']
}
```

package.json

```
"@nuxt/bridge": "npm:@nuxt/bridge-edge",
"nuxt-edge": "latest",
```

**Comment by danielroe** [comment]
this should now be resolved in https://github.com/nuxt/bridge/pull/718.

**Comment by gokalpfirat** [comment]
@danielroe Hello, thanks for the fix but it only resolves iron-webcrypto issue. Even in nuxt-edge there is still an error with nitro: false case

Reproduction link: https://stackblitz.com/edit/nuxt-bridge-h3-issues-ctnwmo?file=package.json

``` 
ERROR  [unhandledRejection] Cannot read properties of undefined (reading 'onError')                              18:12:31

  at toNodeHandle (file://node_modules/nuxi/dist/chunks/index2.mjs:1252:23)
  at Server.serverHandler (file://node_modules/nuxi/dist/chunks/dev.mjs:6767:31)
  at EventEmitter.emit (https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:6:156946)
  at S.emit (https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:6:1536819)
  at parserOnIncoming (https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:6:900393)
  at _0x20faec.parserOnHeadersComplete (https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:6:431488)
  at https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:15:392268
  at _0x5f2925 (https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:15:151290)
  at https://nuxtbridgeh3issuesctnwmo-ncvn.w-credentialless.staticblitz.com/blitz.051cf4f6f83d0fbbae195805e23a344fdd49e233.js:15:151045
```

**Comment by nmackey** [comment]
I am also seeing the error mentioned by @gokalpfirat when using `nitro:false`

**Comment by yusforgithub** [comment]
Have error like @gmcinalli with nitro: false

**Comment by olufemi424** [comment]
```
ERROR  Failed to compile with 1 errors                                                                                         friendly-errors 15:11:43


 ERROR  in ./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs                                                                friendly-errors 15:11:43

Module parse failed: Unexpected token (106:15)                                                                                  friendly-errors 15:11:43
File was processed with these loaders:
 * ./node_modules/unplugin/dist/webpack/loaders/transform.js
You may need an additional loader to handle the result of these loaders.
|     ...input
|   };
>   if (defaults?.params && input?.params) {
|     merged.params = {
|       ...defaults?.params,
                                                                                                                                friendly-errors 15:11:43
 @ ./node_modules/ofetch/dist/index.mjs 1:0-64 2:0-86 2:0-86 2:0-86 23:15-26 26:0-55
 @ ./.nuxt/nitro-bridge.client.mjs
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
                                                                                                                                friendly-errors 15:11:43
✔ Nitro built in 145 ms                                                                                                                 nitro 3:11:44 PM
ℹ Waiting for file changes                     
```

**Comment by Suniron** [comment]
> ```
> ERROR  Failed to compile with 1 errors                                                                                         friendly-errors 15:11:43
> 
> 
>  ERROR  in ./node_modules/ofetch/dist/shared/ofetch.d438bb6f.mjs                                                                friendly-errors 15:11:43
> 
> Module parse failed: Unexpected token (106:15)                                                                                  friendly-errors 15:11:43
> File was processed with these loaders:
>  * ./node_modules/unplugin/dist/webpack/loaders/transform.js
> You may need an additional loader to handle the result of these loaders.
> |     ...input
> |   };
> >   if (defaults?.params && input?.params) {
> |     merged.params = {
> |       ...defaults?.params,
>                                                                                                                                 friendly-errors 15:11:43
>  @ ./node_modules/ofetch/dist/index.mjs 1:0-64 2:0-86 2:0-86 2:0-86 23:15-26 26:0-55
>  @ ./.nuxt/nitro-bridge.client.mjs
>  @ ./.nuxt/index.js
>  @ ./.nuxt/client.js
>  @ multi ./node_modules/eventsource-polyfill/dist/browserify-eventsource.js (webpack)-hot-middleware/client.js?reload=true&timeout=30000&ansiColors=&overlayStyles=&path=%2F__webpack_hmr%2Fclient&name=client ./.nuxt/client.js
>                                                                                                                                 friendly-errors 15:11:43
> ✔ Nitro built in 145 ms                                                                                                                 nitro 3:11:44 PM
> ℹ Waiting for file changes                     
> ```

I think this will be fixed in the next Nuxt Bridge version.

For now, you can add this in your `nuxt.config.ts`:
```ts
  build: {
    postcss: {
      postcssOptions: {
        plugins: {
          autoprefixer: {},
          tailwindcss: {},
        },
      },
    },
    transpile: ['ofetch'],
  },
```

This fix works for me with these versions: 
- @nuxt/bridge-edge 3.0.0-28109745.a6e6787
- nuxt-edge 2.17.1-28110261.f875ec7

**Comment by yusforgithub** [comment]
> With `nitro: false` is error:
> 
> ```
> ERROR  [unhandledRejection] Cannot read property 'onError' of undefined
> 
> at toNodeHandle (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/index2.mjs:490:23)
> at Server.serverHandler (node_modules/@nuxt/bridge/node_modules/nuxi/dist/chunks/dev.mjs:118:31)
> at Server.emit (events.js:412:35)
> at Server.emit (domain.js:475:12)
> at parserOnIncoming (_http_server.js:900:12)
> at HTTPParser.parserOnHeadersComplete (_http_common.js:127:17)
> ```

I changed:

1. file nuxt.config.js
was
```
    bridge: {
        nitro: false,
    },

    runtimeConfig: {
        public: {

        },
    },
```

now
```
    bridge: {
        nitro: false,
    },

    publicRuntimeConfig: {

    },
```
2. file package.json
was
```
{
    "name": "",
    "version": "1.0.0",
    "private": true,
    "scripts": {
        "dev": "HOST=0.0.0.0 nuxi dev",
        "build": "node --max-old-space-size=5120 node_modules/nuxt-edge/bin/nuxt.js build",
        "prod": "HOST=0.0.0.0 nuxi preview",
        "generate": "nuxi generate",
        "analyze": "nuxi build -a",
```

now
```
{
    "name": "",
    "version": "1.0.0",
    "private": true,
    "scripts": {
        "dev": "HOST=0.0.0.0 nuxt",
        "build": "nuxt build",
        "prod": "HOST=0.0.0.0 nuxt start",
        "generate": "nuxt generate",
        "analyze": "nuxt build -a",
```

Now it works.
